/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author Amila
 */
public class AddNewProcess extends javax.swing.JDialog {
    Task_Manager task_Manager;
    int processNo=0;
    ArrayList<ProcessI_OTimePanel> listI_Oope=new ArrayList<ProcessI_OTimePanel>();
    int fullTime;

    /**
     * Creates new form AddNewProcess
     */
    public AddNewProcess(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        task_Manager=(Task_Manager) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        btSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sdFullTime = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        spnNoofI_O = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        proceesI_OTimePanelBar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SdFullTime1 = new javax.swing.JSlider();
        txtFullTime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Add New Process");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 30));

        btCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 100, 40));

        btSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSubmit.setText("Submit");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 100, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Process Identifier");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, 30));
        jPanel1.add(txtPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("No of  I/O operations");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 150, 30));

        sdFullTime.setValue(0);
        sdFullTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdFullTimeStateChanged(evt);
            }
        });
        jPanel1.add(sdFullTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 530, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Process Service Time");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 30));

        spnNoofI_O.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnNoofI_OStateChanged(evt);
            }
        });
        jPanel1.add(spnNoofI_O, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 80, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "I/O Operation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(570, 90));

        proceesI_OTimePanelBar.setAutoscrolls(true);
        proceesI_OTimePanelBar.setPreferredSize(new java.awt.Dimension(570, 90));
        jScrollPane1.setViewportView(proceesI_OTimePanelBar);
        proceesI_OTimePanelBar.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 260));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Process Service Time");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 150, 30));
        jPanel1.add(SdFullTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 550, -1));

        txtFullTime.setText("0");
        txtFullTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFullTimeKeyReleased(evt);
            }
        });
        jPanel1.add(txtFullTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 60, 30));

        jLabel6.setText("ms");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
        task_Manager.addNewPeocess();
         this.dispose();
    }//GEN-LAST:event_btSubmitActionPerformed

    private void spnNoofI_OStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnNoofI_OStateChanged
        proceesI_OTimePanelBar.removeAll();
        listI_Oope=new ArrayList<>();
        int ProcessBarSize=50;
        for (int i = 0; i < Integer.parseInt(spnNoofI_O.getValue()+""); i++) {
            ProcessI_OTimePanel piotp=new ProcessI_OTimePanel(i+1, listI_Oope, fullTime, this);
            piotp.setVisible(true);
            ProcessBarSize+=95;
            proceesI_OTimePanelBar.setPreferredSize(new Dimension(400, ProcessBarSize));
            proceesI_OTimePanelBar.add(piotp);
            proceesI_OTimePanelBar.revalidate();
            listI_Oope.add(piotp);
        }
    }//GEN-LAST:event_spnNoofI_OStateChanged

    private void sdFullTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdFullTimeStateChanged
        fullTime=(sdFullTime.getValue()*20000)/100;
        txtFullTime.setText(fullTime+"");
        for (ProcessI_OTimePanel processI_OTimePanel : listI_Oope) {
            System.out.println("aaaaaaa");
            processI_OTimePanel.update(fullTime);
        }
    }//GEN-LAST:event_sdFullTimeStateChanged

    private void txtFullTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullTimeKeyReleased
        int newFullTime=Integer.parseInt(txtFullTime.getText());
        if(newFullTime<=20000){
            int value=(newFullTime*100)/20000;
            sdFullTime.setValue(value);
            for (ProcessI_OTimePanel processI_OTimePanel : listI_Oope) {
                processI_OTimePanel.update(Integer.parseInt(txtFullTime.getText()));
            }
            fullTime=newFullTime;
        }
    }//GEN-LAST:event_txtFullTimeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewProcess dialog = new AddNewProcess(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider SdFullTime1;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel proceesI_OTimePanelBar;
    private javax.swing.JSlider sdFullTime;
    private javax.swing.JSpinner spnNoofI_O;
    private javax.swing.JTextField txtFullTime;
    private javax.swing.JTextField txtPID;
    // End of variables declaration//GEN-END:variables
}
